import type { Metadata } from 'next';
import { SITE, SITE_URL } from '@/config/site';

export interface BuildMetadataInput {
  title: string;
  description: string;
  /** Absolute path beginning with "/", e.g. "/finance/emi-calculator". */
  path: string;
  keywords?: string[];
  ogType?: 'website' | 'article';
  /** When true, tells search engines not to index (used for utility routes). */
  noindex?: boolean;
  /** ISO date — emitted as article:modified_time for freshness signals. */
  updatedAt?: string;
}

export function absoluteUrl(path: string): string {
  if (path.startsWith('http')) return path;
  return `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;
}

/**
 * Single source of truth for page metadata. Guarantees a canonical URL, OpenGraph
 * and Twitter cards on every page, so an indexable page without unique metadata is
 * impossible.
 */
export function buildMetadata(input: BuildMetadataInput): Metadata {
  const canonical = absoluteUrl(input.path);

  // The brand suffix is appended here, once, and only if it is not already present.
  // `absolute` bypasses the root layout's title.template so it can never double up.
  const base = input.title.trim();
  const hasBrand = base.startsWith(SITE.name) || base.endsWith(SITE.name);
  const fullTitle = hasBrand ? base : `${base} | ${SITE.name}`;

  return {
    title: { absolute: fullTitle },
    description: input.description,
    keywords: input.keywords,
    alternates: { canonical },
    robots: input.noindex
      ? { index: false, follow: true }
      : { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
    openGraph: {
      type: input.ogType ?? 'website',
      url: canonical,
      siteName: SITE.name,
      title: fullTitle,
      description: input.description,
      locale: SITE.locale,
      // The OG image is supplied by the co-located opengraph-image.tsx for each
      // route (per-tool / per-category), falling back to app/opengraph-image.tsx.
      ...(input.updatedAt ? { modifiedTime: input.updatedAt } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description: input.description,
      site: SITE.twitter,
    },
  };
}

/** Root metadata: applied in app/layout.tsx, extended per-page. */
export const ROOT_METADATA: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE.name} — ${SITE.tagline}`,
    template: `%s | ${SITE.name}`,
  },
  description: SITE.description,
  applicationName: SITE.name,
  authors: [{ name: SITE.company.name, url: SITE.company.url }],
  creator: SITE.company.name,
  publisher: SITE.company.name,
  formatDetection: { telephone: false, email: false, address: false },
  // Favicon comes from app/icon.svg automatically; manifest is generated by app/manifest.ts.
  manifest: '/manifest.webmanifest',
};
